# Generated by Django 4.2 on 2024-09-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend_name', models.CharField(max_length=250, verbose_name='janr_name:')),
                ('brend_slug', models.SlugField(max_length=250, verbose_name='slug:')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='category_name:')),
                ('category_slug', models.SlugField(max_length=250, verbose_name='slug:')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ati:')),
                ('price', models.IntegerField(verbose_name='senasi:')),
                ('image1', models.ImageField(upload_to='', verbose_name='suwret_1:')),
                ('image2', models.ImageField(upload_to='', verbose_name='suwret_2:')),
                ('image3', models.ImageField(upload_to='', verbose_name='suwret_3:')),
                ('sani', models.ImageField(upload_to='', verbose_name='sani:')),
                ('discriptions', models.TextField(verbose_name='discriptions:')),
                ('model_protsessor', models.CharField(max_length=50, verbose_name='Model protsessor:')),
                ('operativnaya_pamyat', models.IntegerField(max_length=50, verbose_name='Operativnaya pamyat (gb):')),
                ('disk_xotirasi', models.IntegerField(max_length=50, verbose_name='Disk xotirasi (gb):')),
                ('display_olchami', models.IntegerField(max_length=50, verbose_name="Displey o'lchami:")),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_shop.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_shop.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='comments_date:')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_shop.brend')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
