# Generated by Django 4.2 on 2024-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brend',
            options={'verbose_name': 'Brend', 'verbose_name_plural': 'Brends'},
        ),
        migrations.AlterField(
            model_name='product',
            name='disk_xotirasi',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Disk xotirasi (gb):'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_olchami',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name="Displey o'lchami:"),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_protsessor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model protsessor:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operativnaya_pamyat',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Operativnaya pamyat (gb):'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sani',
            field=models.IntegerField(verbose_name='sani:'),
        ),
    ]
